Revert "[docker] Export PostgreSQL port"
This reverts commit 56823bb

Needs some further investigation as it makes the Travis build fail with:

ERROR: for postgres  driver failed programming external connectivity
on endpoint ginger_postgres_1 (...): Error starting userland proxy:
listen tcp 0.0.0.0:5432: bind: address already in use